Fix/docstring warnings
NeuralEnsemble/elephant pull request #478
Opened 2022-04-19 09:57 UTC by Moritz-Alexander-Kern

This PR fixes mostly indentation errors in several doc-strings. The content of the documentation is not affected.

**Before:**
when building the documentation with:
```
cd doc && make html
```
miscellaneous warnings appeared, most of them indentation errors.
See log of `make html`: [Warnings_log_8_make html.txt](https://github.com/NeuralEnsemble/elephant/files/8511934/Warnings_log_8_make.html.txt)

**With this PR:**
- fixed indentations
- added new template to document classes

2022-04-21 15:06 UTC, mdenker requested changes

2022-04-22 18:31 UTC, Moritz-Alexander-Kern commented on elephant/gpfa/gpfa.py
> -    Methods
This seems to be connected to the way [Sphinx autosummary-extension](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#confval-autosummary_generate) works.

## Methods
Autosummary collects the docstrings from each method and attribute of `class GPFA`. If methods and attributes are already listed in the docstring of the class GPFA itself, e.g. here:
https://github.com/NeuralEnsemble/elephant/blob/7f2a01cc50e36acdfc276cf359c430e9621de43d/elephant/gpfa/gpfa.py#L194-L199
Autosummary will write this docstring + the collected docstrings from each method, hence "Methods" appears twice in the html-files. 

## Attributes
For the attributes a similar  problem occurs. In addition to the above, Autosummary seems to collect class attributes, but no instance attributes. Hence two sections are created, one from the class docstring and one from the docstring of the class attribute (In this case it is `binsize`, which is deprecated).  

## Example from Pandas
Pandas uses  "custom" templates for autosummary. 

_We have two autosummary templates for classes._

1.    __templates/autosummary/class.rst. Use this when you want to automatically generate a page for every public method and attribute on the class. The Attributes and Methods sections will be automatically added to the class’ rendered documentation by numpydoc. See DataFrame for an example._

1.    __templates/autosummary/class_without_autosummary. Use this when you want to pick a subset of methods / attributes to auto-generate pages for. When using this template, you should include an Attributes and Methods section in the class docstring. See CategoricalIndex for an example._

Source: https://pandas.pydata.org/docs/development/contributing_documentation.html#id1

2022-07-04 11:58 UTC, Moritz-Alexander-Kern commented on elephant/gpfa/gpfa.py
> -    Methods
We concluded to proceed with this PR after PR #488 .
This will resolve the conversation above.

2022-11-07 16:05 UTC, Moritz-Alexander-Kern commented on elephant/gpfa/gpfa.py
> -    Methods
Fixed, see also here:

https://elephant--478.org.readthedocs.build/en/478/reference/_toctree/gpfa/elephant.gpfa.gpfa.GPFA.html#elephant.gpfa.gpfa.GPFA

2022-11-16 09:14 UTC, Moritz-Alexander-Kern reviewed
build wheels

2022-11-29 09:00 UTC, Moritz-Alexander-Kern reviewed
build wheels

2023-02-16 08:43 UTC, mdenker approved these changes

2023-02-16 09:13 UTC, merged