add "try it on ebrains" button for elephant tutorials
NeuralEnsemble/elephant pull request #538
Opened 2023-01-27 15:51 UTC by Moritz-Alexander-Kern

This PR adds a "Try it on EBRAINS" next to "Launch on MyBinder" button for the elephant tutorials in the documentation.

Currently the button used is from the NEST website:

https://nest-simulator.org/TryItOnEBRAINS.png

2023-02-16 14:18 UTC, Moritz-Alexander-Kern reviewed
build wheels

2023-02-23 11:11 UTC, mdenker requested changes

2023-02-23 11:11 UTC, mdenker commented on doc/tutorials.rst
> +Launching a notebook on ebrains and Binder both provide a convenient way to
```suggestion
Launching a notebook on EBRAINS and Binder both provide a convenient way to
```

2023-02-23 11:11 UTC, mdenker commented on doc/tutorials.rst
> +changes made to a notebook launched on ebrains are persistent and bound to the
```suggestion
changes made to a notebook launched on EBRAINS are persistent and bound to the
```

2023-02-23 11:11 UTC, mdenker commented on doc/tutorials.rst
> +user's ebrains account. This makes ebrains a great choice if you want to save
```suggestion
user's EBRAINS account. This makes EBRAINS a great choice if you want to save
```

2023-02-23 11:11 UTC, mdenker commented on doc/tutorials.rst
> +  .. image:: https://img.shields.io/badge/launch-ebrains-brightgreen
```suggestion
  ..
      .. image:: https://img.shields.io/badge/launch-ebrains-brightgreen
```

2023-02-23 13:12 UTC, merged