fix spike_time_tiling_coefficient
NeuralEnsemble/elephant pull request #564
Opened 2023-05-12 14:33 UTC by Moritz-Alexander-Kern

This is related to Issue #563 .

The example from the Issue now returns:

- STTC for E7 and E3: 1.0  (Spiketrains identical)
- STTC for E8 and B3: -0.02 (Spiketrains different)

Example Code:
```python
import neo

import quantities as pq

from elephant.spike_train_correlation import spike_time_tiling_coefficient

spiketrain_E7 = neo.SpikeTrain([ 1678. , 23786.3, 34641.8, 71520.7, 73606.9, 78383.3,
97387.9, 144313.4, 4607.6, 19275.1, 152894.2, 44240.1], units='ms', t_stop=160000*pq.ms)

spiketrain_E3 = neo.SpikeTrain([ 1678. , 23786.3, 34641.8, 71520.7, 73606.9, 78383.3,
97387.9, 144313.4, 4607.6, 19275.1, 152894.2, 44240.1], units='ms', t_stop=160000*pq.ms)

print(spike_time_tiling_coefficient(spiketrain_E7, spiketrain_E3, dt=0.10 * pq.s))

spiketrain_E8 = neo.SpikeTrain([ 20646.8, 25875.1, 26154.4, 35121. , 55909.7, 79164.8,
110849.8, 117484.1, 3731.5, 4213.9, 119995.1, 123748.1,
171016.8, 172989. , 185145.2, 12043.5, 185995.9, 186740.1,
12629.8, 23394.3, 34993.2], units='ms', t_stop=210000*pq.ms)

spiketrain_B3 = neo.SpikeTrain([ 10600.7, 19699.6, 22803. , 40769.3, 121385.7, 127402.9,
130829.2, 134363.8, 1193.5, 8012.7, 142037.3, 146628.2,
165925.3, 168489.3, 175194.3, 10339.8, 178676.4, 180807.2,
201431.3, 22231.1, 38113.4], units='ms', t_stop=210000*pq.ms)

print(spike_time_tiling_coefficient(spiketrain_E8, spiketrain_B3, dt=0.10 * pq.s))

```

2023-10-27 14:49 UTC, pep8speaks commented
Hello @Moritz-Alexander-Kern! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`elephant/test/test_spike_train_correlation.py`](https://github.com/NeuralEnsemble/elephant/blob/7d2e3dfe4a7422a894496a2e08bacc150b626c4e/elephant/test/test_spike_train_correlation.py):

> [Line 845:91](https://github.com/NeuralEnsemble/elephant/blob/7d2e3dfe4a7422a894496a2e08bacc150b626c4e/elephant/test/test_spike_train_correlation.py#L845): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 866:5](https://github.com/NeuralEnsemble/elephant/blob/7d2e3dfe4a7422a894496a2e08bacc150b626c4e/elephant/test/test_spike_train_correlation.py#L866): [E301](https://duckduckgo.com/?q=pep8%20E301) expected 1 blank line, found 0

2023-10-27 14:54 UTC, mdenker requested changes
After pair programming review, the following was identified:
- new implementation was checked against pen and paper solution, based on the spike trains generated in the test setup. The validation test against the c implementation should check against this example as well.
- Adding a third spike train to the validation unit test would be good. For the existing validation unit test based on the regression test, it should be noted that this test has no overlaps between spikes -- therefore it tests for PA=PB=0.
- Additional comments for the new improved implementation and for the validation code calling the original c code would be nice.

2023-10-30 09:34 UTC, Moritz-Alexander-Kern commented
>     * new implementation was checked against pen and paper solution, based on the spike trains generated in the test setup. The validation test against the c implementation should check against this example as well.

Added this example to `generate_results.py` , see PR on GIN: https://gin.g-node.org/NeuralEnsemble/elephant-data/pulls/4

>     * Adding a third spike train to the validation unit test would be good. For the existing validation unit test based on the regression test, it should be noted that this test has no overlaps between spikes -- therefore it tests for PA=PB=0.

Generated two spiketrains with:
```python
# Generate two spiketrains with different firing rates
np.random.seed(0)
spiketrain_5_hz = StationaryPoissonProcess(rate=5*pq.Hz, t_start=0*pq.ms, t_stop=5000*pq.ms, refractory_period=3*pq.ms).generate_spiketrain()
spiketrain_30_hz = StationaryPoissonProcess(rate=30*pq.Hz, t_start=0*pq.ms, t_stop=5000*pq.ms, refractory_period=3*pq.ms).generate_spiketrain()
```
The STTC for this example using `dt=100ms` is: `0.5445476264987906`

>     * Additional comments for the new improved implementation and for the validation code calling the original c code would be nice.

Added comments for `run_t` and `run_p` functions, added comments to the Cython code in `wrapper_spike_time_tiling_coefficient.pyx`, see PR on GIN.

2023-10-30 16:36 UTC, mdenker approved these changes

2023-10-30 17:47 UTC, Moritz-Alexander-Kern reviewed
build wheels

2023-10-31 11:19 UTC, merged