Fix/dither spike train with numpy>1.23.0
NeuralEnsemble/elephant pull request #589
Opened 2023-08-01 12:37 UTC by Moritz-Alexander-Kern

This PR addresses issue #586 .

### Changes
- refactor unit tests using `setUpClass`
- add regression test for issue #586 
- refactoring `dither_spikes` function
- updated docstrings
- added typehints

### Notes
- option `edges` has no effect if `refractory_period` is of type `pq.Quantity `
- no default value for `dither`, e.g. use `0 * pq.s` and just return copies of the input spiketrain ? similar to the behavior of passing an empty spiketrain as input ?

2023-08-01 12:56 UTC, Moritz-Alexander-Kern commented
Failing unit tests fixed: #588

2023-09-11 09:22 UTC, Moritz-Alexander-Kern commented
Elephant meeting:
- there is no  default value for dither.

2023-09-14 07:09 UTC, Moritz-Alexander-Kern commented on elephant/spike_train_surrogates.py
> +                train * units.rescale(pq.ms).round(decimals).rescale(units),
`rescale` will act on the units here, thanks to Cristiano for pointing out this Issue.

2023-09-14 12:37 UTC, kohlerca requested changes
With the suggestion to change the part in the code for the `decimals` parameter, the PR will be ready for merging. It is important to note that as the unit tests did not fail (because no rounding was happening), at some point in the future the logic of the unit tests should be checked if it is actually testing the rounding behavior.

2023-09-14 13:19 UTC, Moritz-Alexander-Kern commented on elephant/spike_train_surrogates.py
> +                train * units.rescale(pq.ms).round(decimals).rescale(units),
Thanks for pointing this out, fixed by adding suggested parenthesis.

2023-09-14 13:47 UTC, merged