[ENH] Move to pyproject.toml
NeuralEnsemble/elephant pull request #608
Opened 2023-11-22 14:26 UTC by Moritz-Alexander-Kern

This PR moves Elephant from setup.py to pyproject.toml, aligning with PEP 518.

Key changes include:

- Introduction of `pyproject.toml`
- `setup.py` is still needed to compile the C-code for the fim module.

2023-11-22 14:36 UTC, Moritz-Alexander-Kern reviewed
build wheels

2023-11-22 14:49 UTC, Moritz-Alexander-Kern reviewed
build wheels

2023-11-22 14:55 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-04-04 14:36 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-04 13:46 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-04 13:51 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-04 13:53 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-04 13:55 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-04 13:57 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-04 13:58 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-04 14:15 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-04 14:18 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-04 14:20 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-04 15:12 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-16 08:20 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-16 08:25 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-09-16 08:31 UTC, Moritz-Alexander-Kern reviewed
build wheels

2024-10-11 07:24 UTC, Moritz-Alexander-Kern commented
Editable install with `setup.py` will be deprecated with pip 25.0

> DEPRECATION: Legacy editable install of elephant==1.2.0b1 from file:/// (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457

2025-01-24 12:55 UTC, Moritz-Alexander-Kern reviewed
build wheels

2026-03-16 15:50 UTC, CozySocksAlways commented
- [ ] Update requirements file to remove upper bound matplot lib (notebooks were okay as well as sphinx docs).
- [ ] Add viziphant to tutorials requirements.

2026-04-22 08:29 UTC, CozySocksAlways commented on setup.py
> +        #optional=True
Why was this commented out? 
- Was added in  #494 to overcome the compile fail issue, but didn't work at the time with development (editable) install?
- Commenting it out will cause `optional` defaulting to `None` which is Falsy. So install fails on build?

2026-04-22 12:55 UTC, CozySocksAlways reviewed
trigger build wheels ci

2026-05-27 14:47 UTC, CozySocksAlways commented
Postponing addition of GPU tests with group runner available on jugit.fz-juelich.de to a different PR.

2026-05-27 14:48 UTC, CozySocksAlways commented
Once PR approved, full CI should be triggered. (Run once for each PR approval)

2026-05-28 08:36 UTC, mdenker requested changes
Thank you for this extensive PR, besides the comment about Python versions, it looks good to me so far -- I guess we need to see how the remaining CI jobs work out. I tested installs on Linux and Windows, which seem to work (including the fim module unter linux). However, the Python 3.8 issue that prevents installation of the package in a uv managed pip environment is something we should address.

2026-05-28 08:36 UTC, mdenker commented on pyproject.toml
> +requires-python = ">=3.8"
I feel like this line is giving me problems when doing the following:
- Create a new environment using `uv venv`
- Doing a `uv pip install .` in the elephant directory
- Calling `uv run python`m which gives me an error about dependencies not being satisfyable:uv responds that while I am currently using Python 3.14, the `reuires-python` indicates >=3.8. This is however incompatible with numpy 2. Therefore, uv fails, as it cannot resolve for any of the support python versions. I do not fully understand this logic, however, I guess we should drop 3.8 despite this being a hot fix. Or maybe I am missing something?

2026-05-28 10:14 UTC, CozySocksAlways commented on pyproject.toml
> +requires-python = ">=3.8"
Yup I could recreate this issue, it's an error from my side. The setup.py on our latest release has a requirement on `python>=3.9`, so I'll fix this now on the toml file. 

As a side note, the latest release of numpy (2.4.6) has a requirement of `python>=3.11`, though lower version of numpy 2.0 still support python 3.9. So we should definitely fix this on our next minor release.

2026-05-28 13:43 UTC, CozySocksAlways commented
Test duplication in case of pull_request_review trigger (i.e. both pull_request_review triggered tests pollutes the existing PR checks summary made with the checks triggered on PR synchronize) is the right behavior on GitHub and cannot be avoided as GitHub treats these two as separate events. Refer https://github.com/orgs/community/discussions/26940

As some form of relief, an if clause has been added on the setup job that makes it only run when pull_request_review is approved and not when a review comment is added.

2026-05-29 15:06 UTC, kohlerca approved these changes
The PR looks good to me. I tested locally in Ubuntu, using `mamba` and `uv`, and the installation succeeds.

2026-06-01 09:16 UTC, CozySocksAlways commented
- [x] Update names of tests for consistency (i.e with MPI and conda)

2026-06-02 09:52 UTC, mdenker approved these changes

2026-06-02 11:42 UTC, merged