[Fix] instantaneous rate with list[neo.SpikeTrain]
NeuralEnsemble/elephant pull request #649
Opened 2024-11-15 14:23 UTC by Moritz-Alexander-Kern

The pull request addresses inconsistent behavior with different options in combination with various inputs, specifically:

**Issue:**
- `pool_spiketrains = True` with `list[spiketrains]` does not pool spiketrains as expected. The output should be a single `neo.AnalogSignal`.

**Fix**
- check for other types, previously only `neo.spiketrainlist` was regarded 
- add tests

2025-01-20 10:19 UTC, Moritz-Alexander-Kern commented on elephant/statistics.py
> +    if isinstance(spiketrains, (neo.core.spiketrainlist.SpikeTrainList, list, tuple)) and (
check if is iterable instead of individual classes

2025-01-21 10:55 UTC, Moritz-Alexander-Kern commented on elephant/utils.py
> +def is_list_neo_spiketrains(obj: object) -> bool:
`is_list_spiketrains`

2025-01-21 10:56 UTC, Moritz-Alexander-Kern commented on elephant/utils.py
> +        raise TypeError("Input must be an iterable (list, tuple, etc.)")
no error raised, return false instead

2025-01-21 10:59 UTC, Moritz-Alexander-Kern commented on elephant/test/test_utils.py
> +
add test with input: spiketrain

2025-01-21 11:01 UTC, Moritz-Alexander-Kern commented on elephant/utils.py
> +        True if obj is an iterable containing only neo.SpikeTrain objects.
make return for single spiketrain explicit

2025-01-21 11:02 UTC, Moritz-Alexander-Kern commented on elephant/utils.py
> +        The object to check. Can be a neo.spiketrainlist, list, tuple or any other iterable.
```suggestion
        The object to check.
```

2025-01-21 11:02 UTC, Moritz-Alexander-Kern commented on elephant/utils.py
> +    Raises
```suggestion

```

2025-05-20 13:39 UTC, kohlerca requested changes
I checked the code and made suggestions. Regarding the proposed solution, this needs to be investigated further to ensure the problem was only due to a wrong class membership check. According to the comment on line 1034, the check that originated the error might be misplaced and redundant.

2025-05-20 13:39 UTC, kohlerca commented on elephant/statistics.py
> +    if is_list_spiketrains(spiketrains) and (pool_spike_trains):
However, analyzing the function flow, the new and old checks for a list of `neo.SpikeTrain` objects may not be needed at all:

- in lines 908-911 it is ensured that there will be an Iterable with at least one spike train
- in lines 913-916 an error will be generated if the input is not an iterable that contains only spike trains

Therefore, at this point, it would be possible to only check if pooling or not the spike trains.

2025-05-20 13:39 UTC, kohlerca commented on elephant/test/test_statistics.py
> +        self.assertEqual(rate.shape[1], self.trial_object.n_spiketrains_trial_by_trial[0])
This test checks for consistency between the dimensions of the computed rate and the data in the Trials objects. However, an additional test against the integer values would protect against errors in implementing the object attributes. These hard expected values are supposed to be known when designing the test data in line 493.

2025-05-20 13:39 UTC, kohlerca commented on elephant/test/test_statistics.py
> +        self.assertEqual(len(rate), self.trial_object.n_trials)
Same comment as above, where the test does not compare directly to the expected values, but retrieves them dynamically from the objects.

2025-05-20 13:39 UTC, kohlerca commented on elephant/test/test_statistics.py
> +        self.assertEqual(len(rate), self.trial_object.n_trials)
Same comment as above, where the test does not compare directly to the expected values, but retrieves them dynamically from the objects.

2025-05-20 13:39 UTC, kohlerca commented on elephant/test/test_statistics.py
> +        self.assertEqual(rate.magnitude.shape[1], self.trial_object.n_spiketrains_trial_by_trial[0])
Same comment as above, where the test does not compare directly to the expected values, but retrieves them dynamically from the objects. The integer in the old test could be updated, and the new one just added as an additional check.

2025-05-20 13:39 UTC, kohlerca commented on elephant/test/test_statistics.py
> +    def test_instantaneous_rate_trials_pool_spiketrains(self):
A suggestion to improve understanding of these unit tests, where the dimensions of the outputs change depending on the pooling, is to include a comment block at the beginning to explicitly state the input dimensions --> expected output dimensions. It would be easier to assess the behavior of the object and what is being tested in each test case.

2026-02-20 16:21 UTC, kohlerca commented on elephant/test/test_statistics.py
> +        #   Trails object with self.n_trials, self.n_spiketrains
Typo

2026-02-20 16:23 UTC, kohlerca commented on elephant/test/test_statistics.py
> +        #   Trails obj with self.n_trials, self.n_spiketrains
Typo

2026-02-20 16:26 UTC, kohlerca commented on elephant/test/test_statistics.py
>          self.assertEqual(rate[0].shape[1], 1)
This could be checked for each element, e.g.,

```
for trial_rate in rate:
    self.assertEqual(trial_rate.shape[1], 1)
```

2026-02-20 16:28 UTC, kohlerca commented on elephant/test/test_statistics.py
> +        #       where n_time_bins = (t_stop-t_start)/sampling_period
For completeness, it is also helpful to check the `.shape[0]` value in this and the other tests below

2026-02-20 16:29 UTC, kohlerca commented on elephant/test/test_statistics.py
> +        self.assertEqual(rate[0].shape[1], self.n_spiketrains)
Also check for each element

2026-02-20 16:34 UTC, kohlerca commented on elephant/statistics.py
Link to the `elephant.trials` module

2026-02-20 16:35 UTC, kohlerca commented on elephant/statistics.py
Typo: True instead of true

2026-02-20 16:35 UTC, kohlerca commented on elephant/statistics.py
Typo: True instead of true

2026-02-20 16:35 UTC, kohlerca commented on elephant/statistics.py
`spiketrains` in backticks as it refers to the function argument

2026-02-20 16:36 UTC, kohlerca commented on elephant/statistics.py
Link to the `elephant.trials` module

2026-02-20 16:36 UTC, kohlerca commented on elephant/statistics.py
No extra line

2026-02-20 16:37 UTC, kohlerca commented on elephant/statistics.py
No extra line

2026-02-20 16:37 UTC, kohlerca commented on elephant/statistics.py
Can go in the same line as the above sentence

2026-02-20 16:39 UTC, kohlerca commented on elephant/statistics.py
> +    output : :class:`neo.core.AnalogSignal`
This needs to be updated as there is no information in the documentation regarding the output structure for each type of pooling. This information is valid only for no pooling.

2026-02-20 16:39 UTC, kohlerca commented on elephant/statistics.py
> +        input spiketrain. ``output.times`` contains the time axis of the rate
spike train

2026-02-24 06:53 UTC, mdenker commented on elephant/statistics.py
>          Time stamp resolution of the spike times. The same resolution will
I think this is a bit confusing, I would rather say time resolution of the resulting rate estimate. If this is set to the time resolution of the spike trains, then there will be no aliasing effect in the rate estimate (at the cose of a rather densely sampled output).

For example: 
Time resolution of the resulting rate estimate. The same resolution will be used for the kernel. To avoid effects of binning, set this value to the time stamp resolution of the spike train.

2026-02-24 07:10 UTC, mdenker commented on elephant/test/test_statistics.py
> +        self.assertEqual(rate[0].shape[1], self.n_spiketrains)
One could test everything with a for loop,
```suggest
for _ in range(self.n_trials):
    self.assertEqual(rate[_].shape[1], self.n_spiketrains)
```

2026-02-24 07:10 UTC, mdenker commented on elephant/test/test_statistics.py
> +        self.assertEqual(rate[0].shape[1], 1)
One could test everything with a for loop,
```suggest
for _ in range(self.n_trials):
    self.assertEqual(rate[_].shape[1], 1)
```

2026-02-24 07:16 UTC, mdenker commented on elephant/statistics.py
> +    output : :class:`neo.core.AnalogSignal`
Yes, this is misleading -- it must specify AnalogSignal or list[AnalogSignal], and explicitly mention all cases as in the unit tests.

2026-02-24 08:16 UTC, mdenker commented
I added an alternative version of the doc string, which uses a table format. Let discuss what's the best way to convey this complex output scenario.

2026-02-24 09:13 UTC, mdenker commented
I have added a merge of the two docstring texts and smallified the table. Please have a look. For some reason, the doc string still prints bad on RTD, "Parameters" and "Returns" look squished on the side. I am not so sure what the reason is, perhaps it's the table that takes too much space...

2026-02-24 09:36 UTC, mdenker commented
As expected, the table breaks the formatting of Parameters and Returns sections. Suggestion: Put the table into the Notes (see current doc build). But maybe there are better ideas... Shorten the table? Secret Sphinx commands?

2026-02-24 13:35 UTC, kohlerca commented
I like the idea of the table. If the RTD is breaking within the Returns section, one option is to use the numbered notes format. Therefore, one can put a sentence such as `For a detailed summary of the possible outputs, see the table in Notes [3]` in Returns. If the notes are numbered instead of a bullet list, this will create a direct link within the documentation, and the table down the page can be easily accessed.

2026-02-24 13:56 UTC, kohlerca commented on elephant/statistics.py
> +        single :class:`neo.core.AnalogSignal` with `n_estimates=1`.
Missing spaces

2026-02-24 13:57 UTC, kohlerca commented on elephant/statistics.py
> +        | ``spiketrains`` type         | ``pool_trials`` | ``pool_spike_trains`` | Return type                    | Output shape (per AnalogSignal)          |
AnalogSignal can be set in italics using single backticks.

2026-02-24 14:01 UTC, kohlerca commented on elephant/statistics.py
> +        `sampling_period`.
Reading the overall docstring, it seems that the cleanest version is to have this generic description and then break into the table. I made the other comment regarding the possibility of linking, which I think can work. The only suggestion would be to stick to a single naming convention for the time axis, as currently the short description mentions `n_bins` and the table plus its textual introduction redefines it to `time`.

2026-02-25 11:31 UTC, mdenker commented
There is not a link from the Returns section to the table in the Notes section.

2026-02-25 14:12 UTC, merged